#!/usr/bin/env bash

set -e

VERSION=3.10.0
ARCH=amd64

sudo /opt/singularity/bin/singularity run --allow-setuid --writable-tmpfs singularity/singularity-bootstrap.sif ${VERSION} ${ARCH}
sudo sh -c 'ls -la /root/singularity-*.tar.xz'
