#!/usr/bin/env bash

set -e

VERSION=3.7.3

sudo /opt/singularity/bin/singularity run --allow-setuid --writable-tmpfs singularity/singularity-bootstrap.sif ${VERSION}
sudo sh -c 'ls -la /root/singularity-*-bin.tar.xz'
